### ISSUE TITLE
erlang-ssl 1:22.3.4.9-1 missing in Packages

### ISSUE THREAD

**Issue by devfaz** [rabbitmq/erlang-debian-package#23]
Hello,

seems like erlang-ssl in version 1:22.3.4.9-1 is missing for xenial. The binary-file exists, but the Packages doesnt contain a suitable entry:

--
erlang-ssl:
  Installed: (none)
  Candidate: 1:22.3.4.8-1
  Version table:
     1:22.3.4.8-1 500
--

 Fabian

**Comment by michaelklishin** [comment]
You haven't specified what repository you are looking at. If it's Bintray, we do not control how/when Bintray indexing happens. Bintray is known to rebuild Debian repositories in a way that makes them unavailable for a period of time. Again, we do not maintain or control this.

**Comment by devfaz** [comment]
Hi,

what's the suggested way to get dpkg packages maintained/build by rabbitmq?

The docs tell me

"
Bintray is a package distribution service. Team RabbitMQ maintains an apt repository on Bintray. When using the repository on Bintray it is recommended that Erlang/OTP is also installed from Bintray.
"

**Comment by devfaz** [comment]
So, if I understand you correctly. The packages Are built by rabbitmq, but then indexed by Bintray which may take some time/broke?
