### ISSUE TITLE
Cloudsmith no longer has packages published for Debian Bullseye

### ISSUE THREAD

**Issue by Lord-Y** [rabbitmq/erlang-debian-package#29]
Hello guys,

I'm reaching you because last version of erlang 23.3.4.XXX is not available on Debian Bullseye. You can see the difference between [Debian version 10](https://cloudsmith.io/~rabbitmq/repos/rabbitmq-erlang/packages/?q=distribution%3Adebian+AND+distribution%3Abuster) and [Debian version 11](https://cloudsmith.io/~rabbitmq/repos/rabbitmq-erlang/packages/?q=distribution%3Adebian+AND+distribution%3Abullseye).

It was problematic for us, so on Debian 11 we are temporary using buster target repository.
Can you guys check what's wrong?

**Comment by michaelklishin** [comment]
We don't publish Erlang 23.x packages for Bullseye because there were Bullseye *and* Docker-specific build failures that we never got to investigate.
So use `buster` for distribution.
