### ISSUE TITLE
Installing Erlang/OTP on Ubuntu 22.04 fails

### ISSUE THREAD

**Issue by karpatra** [rabbitmq/erlang-debian-package#35]
### Describe the bug

I am trying to install the Erlang dependencies on Ubuntu 22..04 image. The  installation fails with NO_PUBKEY error even after adding the key manually using the below command.
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80

### Reproduction steps

1. Spin up a new EC2 instance with 22.04 Ubuntu image in govcloud
2. issue the command  sudo apt-get install curl gnupg apt-transport-https -y
3. Team RabbitMQ's main signing key
curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
## Community mirror of Cloudsmith: modern Erlang repository
curl -1sLf https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

## Add apt repositories maintained by Team RabbitMQ
sudo tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
##
deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
EOF
4.# Update package indices
sudo apt-get update -y

5. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv <KEY>
6.  sudo apt-get update -y
...

### Expected behavior

the command should execute without any error related to public key is not available: NO_PUBKEY

**Comment by karpatra** [comment]
i do see the below error while executing the below command.

$ curl -1sLf https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
gpg: no valid OpenPGP data found.

**Comment by michaelklishin** [comment]
`ppa.novemberain.com` works for me:

```
xh https://ppa.novemberain.com/gpg.E495BB49CC4BBE5B.key
HTTP/2.0 200 OK
accept-ranges: bytes
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 7feb7118abf97d1d-EVN
content-length: 1337
content-type: application/octet-stream
date: Wed, 30 Aug 2023 07:50:15 GMT
etag: "6452c6e5-539"
last-modified: Wed, 03 May 2023 20:41:09 GMT
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=mZe806jSch2F0hRpxa0wugKf0uhfGaWpSmU1PPZRDgwLsc%2F4URLqmsyn%2B5GdesQoB1EHZM2GeOb%2FtHJem92Vl%2BZTYpJoD%2BbAoXHGHUhS5p3BNSzp7E1RYf1f6vs4OROKC3VV0ls%2B"}],"group":"cf-nel","max_age":604800}
server: cloudflare

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQGNBGBJAVUBDADBhHZA6wqZcmWMALb5Q+H/99kuI1xXGSBTm3/sNU21kMzHL+Tm
AJrZbSVHflkNdwjQM+xi2Z04xRYZlmE8VI9v788gKm3ojZ4l089aoMW85R0RLxnl
My9KyUbpNkayOAVWIHj/AG/OMSrF7G3OcQCcDYLyD9PvIpt2vPgn9TunMkqD1G5o
hMUOdBBBnzGrgWco2zbORwPM8O8ETtkcZioSp4AWCj7oA/SaugzBQ/3RzSby+1PT
3cBRJei8RWGK97C9ILzY34SMYa0jj8x183gRRzGlGycyVQhLrHmhozLZFaqBCc5a
0JtEYJy/yWeVvz+JEbx4VXFENQbWc77Qe9JO9iaPNO43HtOxpuxIOFajFHWnk2e7
QSnYlZGZQ/7JRHtRu/GcCuqVf+M6jAVx+7rwjCdJ9ROhHYaCmXXODABUPwO0bWIr
rnJChjSDnQ+aQJgQpcQfITO8FjvVcrQowjMCeIq58nIqq8aBKOEk7xHckQ6BnQSB
KrHjzkM+6k8ccVMAEQEAAbRFQ2xvdWRzbWl0aCBQYWNrYWdlIChyYWJiaXRtcS9y
YWJiaXRtcS1lcmxhbmcpIDxzdXBwb3J0QGNsb3Vkc21pdGguaW8+iQG3BBMBCAAh
BQJgSQFVAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEOSVu0nMS75bjV4L
/1lbtAK4qtksPZRoZQJl+s9U7zj7Sqo7Gz9ke90sqt6O96QgKq0/LzACWoeezk9J
lScTwl1bHg+/TVDdar5pTJf3jOoMxNqpdouF4uhCDhbJkOVYFDUysdYwCvavrF7U
4zYa01jKuMcF1FJ21qqy9uFqfQsxVrvniIu1+tONbiDqPEVZUcd7ffcndCLBEpA2
kbFrCj7nD/G3JrO3F6u3/v27lHbpaTbqiL5ovUj5nEA2ACzEgXP69+2MO/2h7mw1
8kS48QiyTVaZaByN4RwbSmPDDtYXM7Mts59XPaxLrzWEH2wKtpAQdKSaUoTGSwDc
bJJ/QOvTdHqaOSaEWR6tZnSrjdGElaHzK3xIdaTpipg+y6WKOEfM8WPpBmYrTJ2F
KGO+mHZY0OdUqdCZohzNtZnbekZUb88UejEvtnOjxmO/22jZxIU7d8ocIV0l7GFf
GMuKc63PqdMzaztmt+CS0uFscE4kfS3ZyMavW7pRDfB8Y4SqZ17zIdnIfnAucCus
Tg==
=gGzU
-----END PGP PUBLIC KEY BLOCK-----
```

You can also [download the key from GitHub](https://github.com/rabbitmq/signing-keys/releases/tag/3.0).

**Comment by michaelklishin** [comment]
[The docs](https://rabbitmq.com/install-debian.html) use `ppa.novemberain.com`:

```
## Team RabbitMQ's main signing key
curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
## Community mirror of Cloudsmith: modern Erlang repository
curl -1sLf https://ppa.novemberain.com/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
## Community mirror of Cloudsmith: RabbitMQ repository
curl -1sLf https://ppa.novemberain.com/gpg.9F4587F226208342.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null
```

**Comment by michaelklishin** [comment]
Debian and RPM packages served by mirrors are signed by the Cloudsmith RabbitMQ account keys (one for RabbitMQ, one for modern Erlang) when served.

Other packages or the same packages obtained from GitHub are signed by the RabbitMQ core team key. The docs import all of them.
