### ISSUE TITLE
link is dead in readme

### ISSUE THREAD

**Issue by artificial-intelligence** [rabbitmq/erlang-debian-package#36]
### Describe the bug

the link to the public CI is dead for me and I don't know where to look at the public pipeline:

https://ci.rabbitmq.com/teams/main/pipelines/erlang-debian-package

seems there is no dns entry for `ci.rabbitmq.com`

Thanks!

### Reproduction steps

1. open Readme
2. click link
3. no result
...

### Expected behavior

link should work

### Additional context

there seems to be neither an A, AAAA or CNAME Record for `ci.rabbitmq.com`

see: https://dnschecker.org/#A/ci.rabbitmq.com

**Comment by michaelklishin** [comment]
We do not plan on making the pipeline public again.

**Comment by michaelklishin** [comment]
The README was updated to link to our Cloudsmith mirror and Launchpad. Those who want full control over how the packages are produced are welcome to take this source package and build
your own .debs on any supported distribution, then publish to an apt repository of your choice. 

Using [Launchpad](https://launchpad.net/~rabbitmq) can be a middle ground between having full control and having a very widely know mature service that you likely can trust.

**Comment by michaelklishin** [comment]
Perhaps it should be mentioned that there isn't anything unusual about how this package is built. You need:

 * A supported distribution
 * To check out the correct version/distribution branch
 * Follow the standard Debian build practices

All the build time dependencies should be installed by Debian helpers. Our pipelines only
really handle the inputs (this repo changes, upstream Erlang/OTP tags) and publishing to services such as Launchpad and Cloudsmith. That's about it, they are hardly of much value to the public.
