### ISSUE TITLE
"No valid OpenPGP data found" when following install docs

### ISSUE THREAD

**Issue by jorvis** [rabbitmq/erlang-debian-package#40]
### Describe the bug

Specifically the issue is in this step:

curl -1sLf https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

The URL for that key returns 404.

### Reproduction steps

1. curl -1sLf https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
2.
3.
...

### Expected behavior

Expected the key file to be there.

### Additional context

This is following the main install steps here in the README.md

**Comment by michaelklishin** [comment]
See [what RabbitMQ documentation guide uses](https://www.rabbitmq.com/docs/install-debian#cloudsmith-signing-keys):

```
sudo apt-get install curl gnupg apt-transport-https -y

## Team RabbitMQ's main signing key
curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
## Community mirror of Cloudsmith: modern Erlang repository
curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
## Community mirror of Cloudsmith: RabbitMQ repository
curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null
```

Or better yet, see a [Quick Start script](https://www.rabbitmq.com/docs/install-debian#apt-quick-start-cloudsmith).

I will update the README to point to the [signing keys repository on GitHub](https://github.com/rabbitmq/signing-keys/releases).
